// Official environments, by Info.dat name. `v3`: the environment is driven by v3 group lighting
// (lightColorEventBoxGroups …) instead of basic events. Modules live in ./<name>.js.
export const ENVIRONMENTS = [
  ['DefaultEnvironment', 'The First'],
  ['OriginsEnvironment', 'Origins'],
  ['TriangleEnvironment', 'Triangle'],
  ['NiceEnvironment', 'Nice'],
  ['BigMirrorEnvironment', 'Big Mirror'],
  ['DragonsEnvironment', 'Imagine Dragons'],
  ['KDAEnvironment', 'K/DA'],
  ['MonstercatEnvironment', 'Monstercat'],
  ['CrabRaveEnvironment', 'Crab Rave'],
  ['PanicEnvironment', 'Panic! at the Disco'],
  ['RocketEnvironment', 'Rocket League'],
  ['GreenDayEnvironment', 'Green Day'],
  ['GreenDayGrenadeEnvironment', 'Green Day Grenade'],
  ['TimbalandEnvironment', 'Timbaland'],
  ['FitBeatEnvironment', 'FitBeat'],
  ['LinkinParkEnvironment', 'Linkin Park'],
  ['BTSEnvironment', 'BTS'],
  ['KaleidoscopeEnvironment', 'Kaleidoscope'],
  ['InterscopeEnvironment', 'Interscope'],
  ['SkrillexEnvironment', 'Skrillex'],
  ['BillieEnvironment', 'Billie Eilish'],
  ['HalloweenEnvironment', 'Spooky'],
  ['GagaEnvironment', 'Lady Gaga'],
  ['WeaveEnvironment', 'Weave', 'v3'],
  ['PyroEnvironment', 'Fall Out Boy', 'v3'],
  ['EDMEnvironment', 'EDM', 'v3'],
  ['TheSecondEnvironment', 'The Second', 'v3'],
  ['LizzoEnvironment', 'Lizzo', 'v3'],
  ['TheWeekndEnvironment', 'The Weeknd', 'v3'],
  ['RockMixtapeEnvironment', 'Rock Mixtape', 'v3'],
  ['Dragons2Environment', 'Imagine Dragons 2', 'v3'],
  ['Panic2Environment', 'Panic! 2', 'v3'],
  ['QueenEnvironment', 'Queen', 'v3'],
  ['LinkinPark2Environment', 'Linkin Park 2', 'v3'],
  ['TheRollingStonesEnvironment', 'The Rolling Stones', 'v3'],
  ['LatticeEnvironment', 'Lattice', 'v3'],
  ['DaftPunkEnvironment', 'Daft Punk', 'v3'],
  ['HipHopEnvironment', 'Hip Hop', 'v3'],
  ['ColliderEnvironment', 'Collider', 'v3'],
  ['BritneyEnvironment', 'Britney Spears', 'v3'],
  ['Monstercat2Environment', 'Monstercat 2', 'v3'],
  ['MetallicaEnvironment', 'Metallica', 'v3'],
];
